name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pandas pytest

    - name: Run tests with pytest
      run: |
        export PYTHONPATH=$PYTHONPATH:./
        pytest tests/testroutes.py --junitxml=pytest-report.xml

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: pytest-report.xml
