name: LibraryFrontendPython CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set Python version
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pandas pytest

    # Ensure Flask knows where to find templates (optional in some cases)
    - name: Set application variable
      run: echo "FLASK_APP=frontend.py" >> $GITHUB_ENV

    # Run tests
    - name: Run tests with pytest
      run: |
        pytest testroutes.py --junitxml=pytest-report.xml

    # Upload test report
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: pytest-report.xml
